#let heuristicas = (
  (
    nombre: "Visibilidad del Estado del Sistema",
    preguntas: (
      (texto: "¿Se muestra visualmente el estado de carga?", peso: 0.2),
      (texto: "¿Se indica la página actual?", peso: 0.11),
      (texto: "¿Se informa el resultado de acciones?", peso: 0.21),
      (texto: "¿Las páginas vacías o en desarrollo muestran mensajes claros?", peso: 0.16),
      (texto: "¿Los elementos interactivos dan retroalimentación visual?", peso: 0.21),
      (texto: "¿Las migas de pan reflejan la ubicación?", peso: 0.11),
    ),
  ),
  (
    nombre: "Relación entre el Sistema y el Mundo Real",
    preguntas: (
      (texto: "¿La terminología es familiar para el usuario?", peso: 0.2),
      (texto: "¿Enlaces e íconos apuntan a las herramientas correctas?", peso: 0.2),
      (texto: "¿Etiquetas y filtros son claras y sencillas?", peso: 0.15),
      (texto: "¿Contactos están en formato copiable y correcto?", peso: 0.1),
      (texto: "¿Los errores usan lenguaje cotidiano y sugieren solución?", peso: 0.15),
      (texto: "¿Mapas, documentos y redes están bien etiquetados?", peso: 0.1),
      (texto: "¿El lenguaje del chatbot es natural y conversacional?", peso: 0.1),
    ),
  ),
  (
    nombre: "Control y Libertad del Usuario",
    preguntas: (
      (texto: "¿Se vuelve al Inicio con un solo clic?", peso: 0.15),
      (texto: "¿Se puede cambiar entre tipos de programas sin regresar al Inicio?", peso: 0.2),
      (texto: "¿Existe un botón claro para borrar todos los filtros?", peso: 0.2),
      (texto: "¿Los avisos emergentes pueden cerrarse sin interferir la tarea?", peso: 0.15),
      (texto: "¿Es fácil copiar datos de contacto (dirección, teléfono) desde la página?", peso: 0.15),
      (texto: "¿Hay rutas de escape visibles si una acción falla o no aporta resultado?", peso: 0.15),
    ),
  ),
  (
    nombre: "Consistencia y Estándares",
    preguntas: (
      (texto: "¿Los enlaces y menús funcionan igual en todas las páginas?", peso: 0.25),
      (texto: "¿El diseño es coherente?", peso: 0.25),
      (texto: "¿Los controles mantienen el mismo comportamiento?", peso: 0.2),
      (texto: "¿Las etiquetas y términos son consistentes y claros?", peso: 0.2),
      (texto: "¿El logo y las rutas principales llevan siempre al inicio?", peso: 0.1),
    ),
  ),
  (
    nombre: "Prevención de Errores",
    preguntas: (
      (texto: "¿Se ocultan o deshabilitan enlaces no funcionales?", peso: 0.2),
      (texto: "¿El buscador sugiere correcciones o alternativas?", peso: 0.2),
      (texto: "¿Los formularios señalan campos obligatorios y errores?", peso: 0.2),
      (texto: "¿Los enlaces e imágenes rotas se detectan y comunican?", peso: 0.15),
      (texto: "¿Hay opciones claras para recuperar una acción fallida?", peso: 0.15),
      (texto: "¿Los mensajes de error ayudan a resolver el problema?", peso: 0.1),
    ),
  ),
  (
    nombre: "Reconocimiento antes que Recuerdo",
    preguntas: (
      (texto: "¿Se ven los filtros aplicados?", peso: 0.25),
      (texto: "¿Contacto fácil de encontrar?", peso: 0.20),
      (texto: "¿Nombres de programas visibles?", peso: 0.20),
      (texto: "¿Iconos identifican categorías?", peso: 0.15),
      (texto: "¿Buscador sugiere en tiempo real?", peso: 0.10),
      (texto: "¿Se recuerdan búsquedas previas?", peso: 0.10),
    ),
  ),
  (
    nombre: "Flexibilidad y Eficiencia de Uso",
    preguntas: (
      (texto: "¿Los usuarios frecuentes realizan tareas más rápido?", peso: 0.2),
      (texto: "¿Se accede fácilmente a novedades y avisos?", peso: 0.15),
      (texto: "¿Buscador y filtros entregan resultados útiles?", peso: 0.2),
      (texto: "¿La navegación móvil es fluida y responsiva?", peso: 0.2),
      (texto: "¿Hay atajos o accesos directos para tareas comunes?", peso: 0.15),
      (texto: "¿Contactos y redes permiten comunicación rápida?", peso: 0.1),
    ),
  ),
  (
    nombre: "Estética y Diseño Minimalista",
    preguntas: (
      (texto: "¿El diseño es claro y sin elementos innecesarios?", peso: 0.25),
      (texto: "¿La información se lee rápido y es fácil de escanear?", peso: 0.25),
      (texto: "¿Colores y tipografías son coherentes?", peso: 0.15),
      (texto: "¿Los elementos tienen espaciado y alineación adecuados?", peso: 0.15),
      (texto: "¿Las imágenes aportan calidad y contexto?", peso: 0.1),
      (texto: "¿La interfaz transmite confianza y profesionalismo?", peso: 0.1),
    ),
  ),
  (
    nombre: "Ayudar a los Usuarios a Reconocer, Diagnosticar y Recuperarse de Errores",
    preguntas: (
      (texto: "¿Los errores son claros y comprensibles?", peso: 0.2),
      (texto: "¿Se indican pasos o soluciones para continuar?", peso: 0.25),
      (texto: "¿Hay páginas/mensajes para contenido no disponible (404)?", peso: 0.15),
      (texto: "¿Se sugieren alternativas cuando la búsqueda no da resultados?", peso: 0.15),
      (texto: "¿Se informa de fallos de carga o pérdida de conexión sin molestar?", peso: 0.1),
      (texto: "¿\"Próximamente\" indica cuándo o qué debe hacer el usuario?", peso: 0.1),
      (texto: "¿Existen rutas visibles para volver atrás o pedir ayuda?", peso: 0.05),
    ),
  ),
  (
    nombre: "Ayuda y Documentación",
    preguntas: (
      (texto: "¿Hay guía de admisión visible?", peso: 0.15),
      (texto: "¿Existen FAQs o manuales de inscripción?", peso: 0.2),
      (texto: "¿Se distingue contacto técnico vs. académico?", peso: 0.1),
      (texto: "¿Se indican las modalidades de los programas?", peso: 0.15),
      (texto: "¿La sección institucional aporta contexto claro?", peso: 0.1),
      (texto: "¿La ayuda es fácil de buscar y encontrar?", peso: 0.1),
      (texto: "¿Los documentos están actualizados y claros?", peso: 0.1),
      (texto: "¿Hay vías de soporte y tiempos de respuesta?", peso: 0.1),
      (texto: "¿El chatbot proporciona respuestas precisas y útiles?", peso: 0.1),
    ),
  ),
)
